### ISSUE TITLE
Polygon searches with wide polygons yield incorrect results

### ISSUE THREAD

**Issue by camposandro** [astronomy-commons/lsdb#180]
**Bug report**

Polygon searches with very wide polygons, of 180+ degrees of vertex angular separation, yield incorrect results. This is tied to the way our internal dependencies (healpy and sphgeom) handle the spatial queries. 

**Reproducing it**

The following code throws an `AssertionError`:
```
vertices = [(0, 80), (0, -80), (345, -80), (345, 80)]
polygon_search_catalog = small_sky_order1.polygon_search(vertices)
polygon_search_df = polygon_search_catalog.compute()
assert all(0 <= ra <= 200 for ra in polygon_search_df["ra"])
```

The points returned should all be within **0 <= ra <= 200**, but are in fact within **200 <= ra <= 360**. This happens because internally the polygon constructed is the one of smallest area: `[(345, -80), (345, 80), (0, 80), (0, -80)]`.

**Task list**

The way to solve this issue is to subdivide the polygon into at least two subpolygons of at most 180 degree separation, perform the respective spatial queries and join the results. An immediate patch consists of throwing an error whenever the polygon is wider than 180 degrees.

**Before submitting**
Please check the following:

- [X] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [X] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a description of what I expected instead.
- [X] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by camposandro** [comment]
After giving this issue a closer look, we came to the conclusion it shouldn't be our responsibility to figure out which polygon the user is trying to construct from a set of vertices. We'd be making assumptions for the user which in any case is also prone to unexpected behavior. For more complex polygon searches we should instead provide an interface that enables fast join and intersection of region searches. As such, not only would we enable the creation of polygon regions that are wider than 180 degrees, but we would also provide an option toward the use of concave polygons.
