### ISSUE TITLE
Release: remove healpy dependency

### ISSUE THREAD

**Issue by delucchi-cmu** [astronomy-commons/lsdb#516]
## Additional context

Removes healpy dependency. 

## hats release

- [x] tag in github
- [x] confirm on [pypi](https://pypi.org/manage/project/hats/releases/)
- [ ] request new conda-forge version (see [similar issue](https://github.com/conda-forge/hats-feedstock/issues/3)) and approve
- [ ] confirm on [conda-forge](https://anaconda.org/conda-forge/hats)

## lsdb release

- [x] tag in github
- [x] confirm on [pypi](https://pypi.org/manage/project/lsdb/releases/)
- [ ] request new conda-forge version (see [similar issue](https://github.com/conda-forge/hats-feedstock/issues/3))
- [ ] confirm tagged hats version and approve
- [ ] confirm on [conda-forge](https://anaconda.org/conda-forge/lsdb)

## hats-import release

- [x] tag in github
- [ ] confirm on [pypi](https://pypi.org/manage/project/hats-import/releases/)
- [ ] request new conda-forge version (see [similar issue](https://github.com/conda-forge/hats-feedstock/issues/3)) and approve
- [ ] confirm tagged hats version and approve
- [ ] confirm on [conda-forge](https://anaconda.org/conda-forge/hats-import)

## Release announcement

- [ ] send release summary to LSSTC slack #lincc-frameworks-lsdb

**Comment by delucchi-cmu** [comment]
Conda releases are going to be a problem - mocpy hasn't pushed a new version since 0.14. There is an open pull request to do this. We will move forward with pypi releases, and address conda-forge when mocpy is available.

**Comment by delucchi-cmu** [comment]
Release highlights:

[hats v0.4.4](https://github.com/astronomy-commons/hats/releases/tag/v0.4.4)
[hats-import v0.4.2](https://github.com/astronomy-commons/hats-import/releases/tag/v0.4.2)

* margin fine filtering has been removed, in favor of improved coarse filtering by healpix boundary search
* `healpy` removed as dependency! we now use CDS's mocpy and cdshealpix for all healpix math.

[lsdb v0.4.3](https://github.com/astronomy-commons/lsdb/releases/tag/v0.4.3)
* adds a `plot_points` method, used in updated [margin notebook](https://docs.lsdb.io/en/latest/tutorials/margins.html)

**Comment by nevencaplar** [comment]
@delucchi-cmu Can we close this issue and replace with a more focused ticket regarding mocpy conda issue?

**Comment by delucchi-cmu** [comment]
mocpy released new version, and our conda-forge packages are now up-to-date.
